### ISSUE TITLE
Add Invocation number to spell icon + some UI element of Invocation Level

### ISSUE THREAD

**Issue by yoshisman8** [cleannrooster/invocations-spellengine#1]
While the icons for the invocations spells are nice, It can be a bit hard to remember which invocation I am actually using and what my current invocation level actually is. The invocation spell icons should ideally have a number on them to help denote which invocation it is. And ideally, it would also be nice to be able to see what my current invocation level is (perhaps a player buff that is always visible?)

**Comment by cleannrooster** [comment]
Is a feature in the newest version.
